python test_vision_4gpu.py --sortquant --quant 12 --split 4 --log ./test.txt --chunk 4
python test_vision_4gpu.py --sortquant --quant 9 --split 3 --log ./test.txt --chunk 4
python test_vision_4gpu.py --sortquant --quant 6 --split 2 --log ./test.txt --chunk 4
python test_nlp_4gpu.py --sortquant --quant 12 --split 4 --log ./test.txt --chunk 4
python test_nlp_4gpu.py --sortquant --quant 9 --split 3 --log ./test.txt --chunk 4
python test_nlp_4gpu.py --sortquant --quant 6 --split 2 --log ./test.txt --chunk 4
python test_vision_4gpu.py --sortquant --quant 12 --split 4 --log ./test.txt --chunk 4
python test_vision_4gpu.py --sortquant --quant 9 --split 3 --log ./test.txt --chunk 4
python test_vision_4gpu.py --sortquant --quant 6 --split 2 --log ./test.txt --chunk 4
python test_nlp_4gpu.py --sortquant --quant 12 --split 4 --log ./test.txt --chunk 4
python test_nlp_4gpu.py --sortquant --quant 9 --split 3 --log ./test.txt --chunk 4
python test_nlp_4gpu.py --sortquant --quant 6 --split 2 --log ./test.txt --chunk 4